#!/bin/bash
while true; do
echo "password_manager.textの内容を削除しますか？(Yes/Exit/others):" 
read num1 
if [[ $num1 == "Yes" ]]; then
> password_manager.text
echo "password_manager.textに保存されている情報を削除しました"
exit 0
elif [[ $num1 == "others" ]]; then
echo "password_manager.textの内容を出力します"
echo
cat password_manager.text
elif [[ $num1 == "Exit" ]]; then
echo "Exitが押されましたシステムを終了します。"
exit 0
else
echo "Yes/No/others を入力してください"
fi
done

